services:
  site:
    network_mode: "host"
    container_name: docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:a723b54c35a76e947095a20a67d39585bb09c862e6b1adeb8a9f518f95e34fb0
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
