name: Validate Renovate

on:
  pull_request:
    paths:
      - "**/renovate.json"
      - "**/renovate.json5"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install -g renovate@43.150.0

      - name: Validate Renovate config
        run: renovate-config-validator
